# Default values for yesod-postgres-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: psibi/yesod-demo
  tag: 4.0-yesod-demo
  pullPolicy: IfNotPresent

postgresql:
  postgresUser: postgres
  postgresPassword: fajkfjakjfka
  postgresDatabase: yesod-test
  persistence:
    storageClass: ssd-slow

resources:
  yesodapp:
    limits:
      cpu: 0.8
      memory: "500Mi"
    requests:
      cpu: 0.2
      memory: "300Mi"

  nginx:
    limits:
      cpu: "500m"
      memory: "128Mi"
    requests:
      cpu: "250m"
      memory: "64Mi"
      

service:
  type: ClusterIP
  port: 80
