# Default values for yesod-postgres-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: psibi/yesod-demo
  tag: 4.0-yesod-demo
  pullPolicy: IfNotPresent

postgresql:
  postgresUser: postgres
  postgresPassword: fajkfjakjfka
  postgresDatabase: yesod-test
  persistence:
    storageClass: ssd-slow

service:
  type: ClusterIP
  port: 80
