apiVersion: v1
data:
  yesod_static_path: /app/static
  yesod_db_name: yesod-test
  yesod_db_port: "5432"
  yesod_host_name: "{{ .Release.Name  }}-postgresql"
kind: ConfigMap
metadata:
  name: {{ template "yesod-postgres-chart.full_name" . }}-configmap
