kind: Service
apiVersion: v1
metadata:
  name: {{ template "yesod-nginx-resource.full_name" . }}
spec:
  selector:
    {{- include "yesod-nginx-resource.release_labels" . | indent 4 }}
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: LoadBalancer
