apiVersion: v1
kind: Secret
metadata:
  name: {{ template "yesod-postgres-chart.full_name" . }}-secret
type: Opaque
data:
  yesod-db-password: {{ .Values.db.password | b64enc | quote }}
  yesod-db-user: {{ .Values.db.user | b64enc | quote }}
